---
- name: add webupd8team ppa key to apt-key
  apt_key: file=/root/webupd8team_ppa.gpg
  sudo: yes

- name: webupd8team java sources.list
  template: >
    src=webupd8team-java.list.j2
    dest=/etc/apt/sources.list.d/webupd8team-java.list
    force=no
  register: sources_list_result
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes

- name: accept oracle license
  shell: >
    echo "oracle-java8-installer shared/accepted-oracle-license-v1-1
    select true" | debconf-set-selections
  sudo: yes
  changed_when: False

- name: accept oracle license
  shell: >
    echo "oracle-java8-installer shared/accepted-oracle-license-v1-1
    seen true" | debconf-set-selections
  sudo: yes
  changed_when: False
